dist: bionic

sudo: required

language: python
python:
  - "3.7"

before_install:
  # ocrmypdf
  - sudo apt-get update
  - sudo apt-get install -y ocrmypdf
  # Overwrite the ElasticSearch that comes with the Travis CI environment - the changes to jvm.options are done in an
  # attempt to emulate the existing config for Elasticsearch 5.5.
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
  # Solr
  - mkdir ../solr && pushd ../solr
  - curl -s -O https://www-us.apache.org/dist/lucene/solr/8.4.1/solr-8.4.1.tgz
  - tar xzf solr-8.4.1.tgz && ./solr-8.4.1/bin/solr -c -e schemaless
  - popd

install:
  - pip install -r requirements.txt

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      before_script:
      - python -m spacy download en
      script:
      - pytest --verbose --capture=no pdfner/tests/test_api.py --pdf_file=./pdfner/tests/data/gre_research_validity_data.pdf
    - stage: deploy
      deploy:
        provider: pypi
        user: hnluu8
        password:
          secure: Dee5I7jbopgAuEwlf5CY2n7cn/L1zSC6hP5qEua+JfaWzbKr4h8e/4pWKoY18cP19eQrwldZsbs8/FWkK6pavEHliCJo+2iwYmdwvzDNK2SgF/NPJ43VUh8bvaGhG45IGaO+wjC5q/8emrnmBgPmnOKgDySiw5+eXuavRp/RwJ9MzbVMrpi+2/AyBk4Ve0r0ulaptOEHZMx3hLb5bJu3Sy4NJys7kM+mrnBSLQ+6eKVldYa+6L8mNFxQaEjhO3mHsqS/Gzrzq5R6mt+TRvwhTj2+vj9G2fJaiBuQ91a5OqJGrkYQmoMPSrvoa65P8csIV2JKY754pqxqAhU0ZPmXVSyWHEpe/iHMRizPgZubI345kfzWUKN1CZQcZsD3DyTUebv+Ml/QMEtSQmlZ6WQg2gTCTdrueVQFvgYLO2lwaJJMDXqiyWZySUdYTIE9cv5dksg9hueQHpOmHdpTJcSwA8r3qSMvRC8HogL7yJrMSVPqGEybIqPKaQfvDOd7//vBHEXou7YYZa4bIJqrs0trstds1ywJhimJp5wm467Xrbn/TRJSolyIIhKOznxGjxiQLVhJmqCBE2c54Kd/hezNlFEoOOUs5f2grw//H9Ur9y6FwfQhs17/frC9eiu7PSjGasf7kplh8TyCQFaPUWagLPS/xB3r8HIuYIWSCSYYp9k=
        distributions: sdist bdist_wheel
        skip_existing: true

notifications:
  email: false
