sudo: required

language: python
python:
  - "3.7"

before_install:
  # Overwrite the ElasticSearch that comes with the Travis CI environment - the changes to jvm.options are done in an
  # attempt to emulate the existing config for Elasticsearch 5.5.
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch

install: skip

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - pytest --verbose --capture=no pdfner/tests/test_search.py

notifications:
  email: false


