sudo: required

language: python
python:
  - "3.7"

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb.sha512
  - shasum -a 512 -c elasticsearch-7.5.1-amd64.deb.sha512
  - sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb
  - sudo cat /usr/lib/systemd/system/elasticsearch.service

install: skip

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - curl -v http://localhost:9200/

notifications:
  email: false


