sudo: required

language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requirements.txt

stages:
  - test

jobs:
  include:
    - stage: test
      script:
      - pip install -q localstack; docker pull localstack/localstack; localstack start --docker & sleep 20
      - pytest --verbose --capture=no pdfner/tests/test_search.py

notifications:
  email: false


