sudo: required

language: python
python:
  - "3.7"

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.6.deb && sudo dpkg -i --force-confnew elasticsearch-6.8.6.deb && sudo -i service elasticsearch start

install: skip

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - curl -v http://localhost:9200/

notifications:
  email: false


