sudo: required

language: python
python:
  - "3.7"

services:
  - elasticsearch

before_install:
  - sudo service elasticsearch stop
  - sleep 10
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb && sudo service elasticsearch restart

install: skip

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - curl -v http://localhost:9200/

notifications:
  email: false


