sudo: required

language: python
python:
  - "3.7"

before_install:
  - sudo cat /etc/elasticsearch/elasticsearch.yml
  - sudo systemctl status elasticsearch.service

install: skip

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - curl -v http://localhost:9200/

notifications:
  email: false


