sudo: required

language: python
python:
  - "3.7"

install: skip

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - curl -v http://localhost:9200/

notifications:
  email: false


