sudo: false

language: python
python:
  - "3.7"

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb && sudo service elasticsearch restart

install:
  - pip install -r requirements.txt

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
      - sleep 10
      script:
      - pytest --verbose --capture=no pdfner/tests/test_search.py

notifications:
  email: false


